version: "3.8"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    volumes:
      - .:/app
    depends_on:
      - postgresql-test
    env_file:
      - config/test.conf
    networks:
      - test-network

  postgresql-test:
    image: postgres:latest
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    ports:
      - "5430:5432"
    env_file:
      - config/test.conf
    networks:
      - test-network

  goose-test:
    build:
      context: .
      dockerfile: Dockerfile.goose
    volumes:
      - ./migrations:/app/migrations
    env_file:
      - config/test.conf
    networks:
      - test-network
    working_dir: /app

volumes:
  postgres_test_data:


networks:
  test-network:
    driver: bridge
