version: "3.8"
services:

  test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    volumes:
      - .:/app
    depends_on:
      - postgresql-test
    env_file:
      - config/test.conf

  postgresql-test:
    container_name: graphyy-postgresql-test1
    image: postgres:latest
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    ports:
      - "5430:5432"
    env_file:
      - config/test.conf

volumes:
  postgres_test_data:
